package pageobject;

import static org.junit.jupiter.api.Assertions.assertEquals;

// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import io.github.bonigarcia.seljup.BrowserType;
import io.github.bonigarcia.seljup.DockerBrowser;
import io.github.bonigarcia.seljup.SeleniumJupiter;
import pageobject.pages.ConfirmationPage;
import pageobject.pages.HomePage;
import pageobject.pages.PurchasePage;
import pageobject.pages.ReservePage;

@ExtendWith(SeleniumJupiter.class)
public class BuyTest {

  @Test
  public void buyTrip(FirefoxDriver driver) {
    HomePage homePage = new HomePage(driver);
    homePage.selectFromPort("Philadelphia");
    homePage.selectToPort("Rome");

    assertEquals("Welcome to the Simple Travel Agency!", homePage.getTitle());
    assertEquals("Philadelphia", homePage.getFromPort());
    assertEquals("Rome", homePage.getToPort());

    homePage.clickFindFlights();

    ReservePage chooseFlightPage = new ReservePage(driver);

    assertEquals("Flights from Philadelphia to Rome:", chooseFlightPage.getTitle());
    assertEquals("43", chooseFlightPage.getFlightNumber());
    assertEquals("Virgin America", chooseFlightPage.getAirline());
    assertEquals("1:43 AM", chooseFlightPage.getDepartureTime());
    assertEquals("9:45 PM", chooseFlightPage.getArrivalTime());
    assertEquals("$472.56", chooseFlightPage.getPrice());

    chooseFlightPage.clickChooseFlightButton();

    PurchasePage purchasePage = new PurchasePage(driver);

    purchasePage.setFormData(
        "Alex",
        "Aveiro Street",
        "Aveiro",
        "Portugal",
        "3810",
        "Visa",
        "9999",
        "12",
        "2027",
        "John",
        "1");

    assertEquals("Your flight from TLV to SFO has been reserved.", purchasePage.getTitle());
    assertEquals("Alex", purchasePage.getName());
    assertEquals("Aveiro Street", purchasePage.getAddress());
    assertEquals("Aveiro", purchasePage.getCity());
    assertEquals("Portugal", purchasePage.getState());
    assertEquals("3810", purchasePage.getZipCode());
    assertEquals("visa", purchasePage.getCardType());
    assertEquals("9999", purchasePage.getCreditCardNumber());
    assertEquals("12", purchasePage.getCreditCardMonth());
    assertEquals("2027", purchasePage.getCreditCardYear());
    assertEquals("John", purchasePage.getNameOnCard());
    assertEquals("on", purchasePage.getRememberMe());

    purchasePage.clickPurchaseFlight();

    ConfirmationPage confirmationPage = new ConfirmationPage(driver);

    assertEquals("Thank you for your purchase today!", confirmationPage.getTitle());
    assertEquals("PendingCapture", confirmationPage.getStatus());
    assertEquals("555 USD", confirmationPage.getAmount());
    assertEquals("xxxxxxxxxxxx1111", confirmationPage.getCardNumber());
    assertEquals("11 /2018", confirmationPage.getExpirationDate());
    assertEquals("888888", confirmationPage.getAuthCode());
  }

  
  @Test
  public void buyTripDocker(@DockerBrowser(type = BrowserType.CHROME) WebDriver driver) {
    HomePage homePage = new HomePage(driver);
    homePage.selectFromPort("Philadelphia");
    homePage.selectToPort("Rome");

    assertEquals("Welcome to the Simple Travel Agency!", homePage.getTitle());
    assertEquals("Philadelphia", homePage.getFromPort());
    assertEquals("Rome", homePage.getToPort());

    homePage.clickFindFlights();

    ReservePage chooseFlightPage = new ReservePage(driver);

    assertEquals("Flights from Philadelphia to Rome:", chooseFlightPage.getTitle());
    assertEquals("43", chooseFlightPage.getFlightNumber());
    assertEquals("Virgin America", chooseFlightPage.getAirline());
    assertEquals("1:43 AM", chooseFlightPage.getDepartureTime());
    assertEquals("9:45 PM", chooseFlightPage.getArrivalTime());
    assertEquals("$472.56", chooseFlightPage.getPrice());

    chooseFlightPage.clickChooseFlightButton();

    PurchasePage purchasePage = new PurchasePage(driver);

    purchasePage.setFormData(
        "Alex",
        "Aveiro Street",
        "Aveiro",
        "Portugal",
        "3810",
        "Visa",
        "9999",
        "12",
        "2027",
        "John",
        "1");

    assertEquals("Your flight from TLV to SFO has been reserved.", purchasePage.getTitle());
    assertEquals("Alex", purchasePage.getName());
    assertEquals("Aveiro Street", purchasePage.getAddress());
    assertEquals("Aveiro", purchasePage.getCity());
    assertEquals("Portugal", purchasePage.getState());
    assertEquals("3810", purchasePage.getZipCode());
    assertEquals("visa", purchasePage.getCardType());
    assertEquals("9999", purchasePage.getCreditCardNumber());
    assertEquals("12", purchasePage.getCreditCardMonth());
    assertEquals("2027", purchasePage.getCreditCardYear());
    assertEquals("John", purchasePage.getNameOnCard());
    assertEquals("on", purchasePage.getRememberMe());

    purchasePage.clickPurchaseFlight();

    ConfirmationPage confirmationPage = new ConfirmationPage(driver);

    assertEquals("Thank you for your purchase today!", confirmationPage.getTitle());
    assertEquals("PendingCapture", confirmationPage.getStatus());
    assertEquals("555 USD", confirmationPage.getAmount());
    assertEquals("xxxxxxxxxxxx1111", confirmationPage.getCardNumber());
    assertEquals("11 /2018", confirmationPage.getExpirationDate());
    assertEquals("888888", confirmationPage.getAuthCode());
  }

}
